import fs from "fs";
import crypto from "crypto";
import { DEFAULT_DATA_DIR, loadConfig, saveConfig, type EdgebricConfig } from "../lib/paths.js";
import { ask, askSecret, confirm } from "../lib/prompt.js";

export async function setupCommand() {
  console.log();
  console.log("  Edgebric Setup Wizard");
  console.log("  =====================");
  console.log();
  console.log("  This wizard will configure Edgebric for first-time use.");
  console.log("  You can re-run this at any time to update your configuration.");
  console.log();

  const existing = loadConfig();
  if (existing) {
    console.log("  Existing configuration found. Current values shown as defaults.");
    console.log();
  }

  // 1. Data directory
  console.log("  Step 1/4: Data Directory");
  console.log("  Where should Edgebric store its data (database, uploads, logs)?");
  const dataDir = await ask("Data directory", existing?.dataDir ?? DEFAULT_DATA_DIR);
  fs.mkdirSync(dataDir, { recursive: true });
  console.log();

  // 2. OIDC configuration
  console.log("  Step 2/4: Single Sign-On (OIDC)");
  console.log("  Edgebric uses OIDC for authentication. You need credentials from");
  console.log("  your identity provider (Google Workspace, Microsoft 365, Okta, etc.).");
  console.log();
  console.log("  For Google: go to console.cloud.google.com > APIs & Services > Credentials");
  console.log("  Create an OAuth 2.0 Client ID, set redirect URI to:");
  console.log("  http://localhost:3001/api/auth/callback");
  console.log();

  const oidcIssuer = await ask("OIDC Issuer URL", existing?.oidcIssuer ?? "https://accounts.google.com");
  const oidcClientId = await ask("Client ID", existing?.oidcClientId);
  if (!oidcClientId) {
    console.log("\n  Client ID is required. Aborting setup.");
    process.exit(1);
  }

  const oidcClientSecret = await askSecret("Client Secret (hidden)");
  if (!oidcClientSecret && !existing?.oidcClientSecret) {
    console.log("\n  Client Secret is required. Aborting setup.");
    process.exit(1);
  }
  console.log();

  // 3. Admin email
  console.log("  Step 3/4: Admin Access");
  console.log("  Enter the email address(es) that should have admin access.");
  console.log("  Separate multiple emails with commas.");
  const adminInput = await ask("Admin email(s)", existing?.adminEmails?.join(", "));
  const adminEmails = adminInput
    .split(",")
    .map((e) => e.trim().toLowerCase())
    .filter(Boolean);
  if (adminEmails.length === 0) {
    console.log("\n  At least one admin email is required. Aborting setup.");
    process.exit(1);
  }
  console.log();

  // 4. Server port
  console.log("  Step 4/4: Server Port");
  const port = parseInt(await ask("Port", String(existing?.port ?? 3001)), 10);
  console.log();

  // Optional: Chat model config
  const configureLLM = await confirm("Configure a custom LLM endpoint? (default: use local mILM)", false);
  let chatBaseUrl: string | undefined;
  let chatModel: string | undefined;
  if (configureLLM) {
    chatBaseUrl = await ask("Chat API base URL", existing?.chatBaseUrl ?? "http://localhost:8080/v1");
    chatModel = await ask("Chat model name", existing?.chatModel ?? "qwen3.5-4b");
  }

  // Generate session secret
  const sessionSecret = crypto.randomBytes(64).toString("hex");

  const config: EdgebricConfig = {
    dataDir,
    port,
    oidcIssuer,
    oidcClientId,
    oidcClientSecret: oidcClientSecret || existing?.oidcClientSecret || "",
    adminEmails,
    ...(chatBaseUrl && { chatBaseUrl }),
    ...(chatModel && { chatModel }),
  };

  saveConfig(config);

  // Write .env for the API server
  const envPath = `${dataDir}/.env`;
  const envContent = [
    `# Generated by edgebric setup — ${new Date().toISOString()}`,
    `DATA_DIR=${dataDir}`,
    `PORT=${port}`,
    `SESSION_SECRET=${sessionSecret}`,
    `OIDC_ISSUER=${oidcIssuer}`,
    `OIDC_CLIENT_ID=${oidcClientId}`,
    `OIDC_CLIENT_SECRET=${oidcClientSecret || existing?.oidcClientSecret || ""}`,
    `OIDC_REDIRECT_URI=http://localhost:${port}/api/auth/callback`,
    `ADMIN_EMAILS=${adminEmails.join(",")}`,
    `FRONTEND_URL=http://localhost:${port}`,
    ...(chatBaseUrl ? [`CHAT_BASE_URL=${chatBaseUrl}`] : []),
    ...(chatModel ? [`CHAT_MODEL=${chatModel}`] : []),
    "",
  ].join("\n");
  fs.writeFileSync(envPath, envContent, "utf8");

  console.log("  Setup complete!");
  console.log();
  console.log(`  Configuration saved to: ${config.dataDir}/.edgebric.json`);
  console.log(`  Environment file:       ${envPath}`);
  console.log();
  console.log("  Next steps:");
  console.log(`    edgebric start       Start the server`);
  console.log(`    Open http://localhost:${port} in your browser`);
  console.log();
}
