#!/usr/bin/env python3.11
"""
Spike 2 — mKB real test against running mimik mKB microservice.

Tests the full flow against the actual mKB API:
  1. Create dataset
  2. Embed chunks via real mILM
  3. Upload chunks (multipart/form-data with JSON file)
  4. Search by embedding
  5. Clean up

Key findings from probing:
  - Chunk upload: POST /datasets/{name}/chunks as multipart/form-data
    File field named "file", JSON array of {chunkId, chunk, embedding, metadata}
  - Search: POST /search with {datasetName, embedding, topN}
  - Auth header: "bearer" (lowercase)
"""

import email.mime.multipart
import email.mime.base
import io
import json
import math
import time
import urllib.request
import urllib.parse
from pathlib import Path

# ── Config ─────────────────────────────────────────────────────────────────────
MKB_BASE = "http://localhost:8083/api/mkb/v1"
MILM_BASE = "http://localhost:8083/api/mim/v1"
API_KEY_FILE = Path(__file__).parent.parent.parent / "scripts/binaries/mim-OE-ai/.milm_api_key"
API_KEY = API_KEY_FILE.read_text().strip()

EMBED_MODEL = "nomic-embed-text"
DATASET_NAME = "spike2-hr-policy"
TOP_N = 3
SIMILARITY_THRESHOLD = 0.60


# ── Test chunks ─────────────────────────────────────────────────────────────────
CHUNKS = [
    {
        "id": "chunk-001",
        "text": "New employees receive 15 days of paid time off (PTO) during their first year of employment. PTO accrues at a rate of 1.25 days per month.",
        "metadata": {"section": "Time Off Policy", "page": 12},
    },
    {
        "id": "chunk-002",
        "text": "Remote work is permitted for eligible positions up to 3 days per week with manager approval. Employees must maintain availability during core hours of 10am-3pm in their local timezone.",
        "metadata": {"section": "Remote Work Policy", "page": 18},
    },
    {
        "id": "chunk-003",
        "text": "The Gold health plan has a $500 individual deductible and a $1,000 family deductible. Monthly premiums are $150 for individual and $400 for family coverage.",
        "metadata": {"section": "Benefits - Health Insurance", "page": 24},
    },
    {
        "id": "chunk-004",
        "text": "Primary caregivers receive 12 weeks of fully paid parental leave. Secondary caregivers receive 4 weeks of fully paid parental leave.",
        "metadata": {"section": "Parental Leave", "page": 30},
    },
    {
        "id": "chunk-005",
        "text": "Employees are expected to maintain professional conduct in the workplace. Business casual attire is standard. The dress code is enforced Monday through Friday.",
        "metadata": {"section": "Workplace Conduct", "page": 8},
    },
]

TEST_QUERIES = [
    # (query, answerable, expected_chunk_index)
    # mKB auto-generates IDs as {datasetName}-{0-indexed-position}
    ("How much PTO do new employees get?", True, 0),       # chunk-001 → index 0
    ("What is the remote work policy?", True, 1),          # chunk-002 → index 1
    ("What is the Gold health plan deductible?", True, 2), # chunk-003 → index 2
    ("What is the dress code for the Tokyo office?", False, None),  # WARN expected
]


# ── Helpers ─────────────────────────────────────────────────────────────────────

def api_request(method: str, url: str, body: bytes | None = None,
                content_type: str = "application/json") -> dict:
    headers = {
        "Authorization": f"bearer {API_KEY}",
    }
    if content_type:
        headers["Content-Type"] = content_type

    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        body_text = e.read().decode()
        raise RuntimeError(f"HTTP {e.code} {method} {url}: {body_text}")


def embed(text: str) -> list[float]:
    result = api_request(
        "POST", f"{MILM_BASE}/embeddings",
        body=json.dumps({"model": EMBED_MODEL, "input": text}).encode(),
    )
    return result["data"][0]["embedding"]


def cosine_sim(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    mag = math.sqrt(sum(x**2 for x in a)) * math.sqrt(sum(x**2 for x in b))
    return dot / mag if mag else 0.0


def build_ndjson_multipart(chunks: list[dict]) -> tuple[bytes, str]:
    """Build multipart/form-data with NDJSON file in 'chunks' field.

    mKB source-confirmed format:
    - Form field name: "chunks" (not "file")
    - Content: NDJSON lines joined by \\n\\n
    - First line: {"chunkTotal": N, "searchPrefix": null}
    - Remaining lines: {"chunk": "text", "embedding": [...]}
    - chunkId is auto-generated by mKB as {datasetName}-{index}
    """
    lines = [json.dumps({"chunkTotal": len(chunks), "searchPrefix": None})]
    for c in chunks:
        lines.append(json.dumps({"chunk": c["text"], "embedding": c["embedding"]}))
    ndjson_content = "\n\n".join(lines)

    boundary = "----EdgebricBoundary7MA4YWxkTrZu0gW"
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="chunks"; filename="chunks.mdf"\r\n'
        f"Content-Type: application/octet-stream\r\n\r\n"
    ).encode() + ndjson_content.encode("utf-8") + f"\r\n--{boundary}--\r\n".encode()

    content_type = f"multipart/form-data; boundary={boundary}"
    return body, content_type


def upload_chunks(dataset_name: str, chunks: list[dict]) -> None:
    """Upload embedded chunks to mKB via multipart/form-data (NDJSON format)."""
    body, content_type = build_ndjson_multipart(chunks)

    headers = {
        "Authorization": f"bearer {API_KEY}",
        "Content-Type": content_type,
    }
    req = urllib.request.Request(
        f"{MKB_BASE}/datasets/{urllib.parse.quote(dataset_name)}/chunks",
        data=body,
        headers=headers,
        method="POST",
    )
    try:
        # Response is SSE streaming — read it but don't try to parse as JSON
        with urllib.request.urlopen(req, timeout=60) as resp:
            return resp.read().decode()
    except urllib.error.HTTPError as e:
        raise RuntimeError(f"uploadChunks HTTP {e.code}: {e.read().decode()}")


def search_mkb(dataset_name: str, prompt: str, top_n: int = 3) -> list[dict]:
    """Search mKB by prompt text (mKB calls mILM internally to embed).

    mKB source-confirmed: search uses 'prompt' (text), not 'embedding'.
    GEN_AI_EMBEDDING_URI env var makes mKB auto-embed via mILM.
    """
    result = api_request(
        "POST", f"{MKB_BASE}/search",
        body=json.dumps({
            "datasetName": dataset_name,
            "prompt": prompt,
            "topN": top_n,
        }).encode(),
    )
    # Response may be wrapped in data or direct list
    if isinstance(result, list):
        return result
    return result.get("data", [])


# ── Main ────────────────────────────────────────────────────────────────────────

def main():
    print(f"\n{'='*65}")
    print("Spike 2 — mKB real test against mimik mKB v1.3.0")
    print(f"{'='*65}\n")

    # ── Step 0: Clean up any previous dataset ─────────────────────────────────
    print("Step 0: Cleaning up any previous test dataset...")
    try:
        api_request("DELETE", f"{MKB_BASE}/datasets/{urllib.parse.quote(DATASET_NAME)}")
        print(f"  Deleted existing '{DATASET_NAME}'")
    except Exception:
        print(f"  No existing dataset to delete (expected on first run)")

    # ── Step 1: Create dataset ─────────────────────────────────────────────────
    print(f"\nStep 1: Creating dataset '{DATASET_NAME}'...")
    result = api_request(
        "POST", f"{MKB_BASE}/datasets",
        body=json.dumps({"datasetName": DATASET_NAME, "model": EMBED_MODEL}).encode(),
    )
    print(f"  Created: {result}")

    # ── Step 2: Embed all chunks via mILM ─────────────────────────────────────
    print(f"\nStep 2: Embedding {len(CHUNKS)} chunks via real mILM...")
    t0 = time.time()
    for chunk in CHUNKS:
        emb = embed(chunk["text"])
        chunk["embedding"] = emb
        print(f"  [{chunk['id']}] {len(emb)} dims — {chunk['metadata']['section']}")
    print(f"  Embedding time: {time.time()-t0:.1f}s")

    # ── Step 3: Upload chunks to mKB ──────────────────────────────────────────
    print(f"\nStep 3: Uploading {len(CHUNKS)} chunks to mKB (multipart/form-data)...")
    t0 = time.time()
    upload_chunks(DATASET_NAME, CHUNKS)
    print(f"  Upload time: {time.time()-t0:.1f}s")

    # Verify dataset now has chunks
    datasets = api_request("GET", f"{MKB_BASE}/datasets")
    ds_list = datasets.get("data", datasets) if isinstance(datasets, dict) else datasets
    our_ds = next((d for d in (ds_list if isinstance(ds_list, list) else []) if d.get("datasetName") == DATASET_NAME), None)
    if our_ds:
        print(f"  Dataset now has {our_ds.get('numberOfChunks', '?')} chunks")

    # ── Step 4: Similarity search tests ──────────────────────────────────────
    print(f"\nStep 4: Similarity search tests")
    print("=" * 65)

    results_summary = []
    for query, answerable, expected_id in TEST_QUERIES:
        print(f"\nQ: {query}")

        results = search_mkb(DATASET_NAME, query, TOP_N)

        if not results:
            print("  No results returned!")
            results_summary.append((query, answerable, "FAIL"))
            continue

        top = results[0]
        top_id = top.get("chunkId", top.get("id", "?"))
        top_score = top.get("similarity", top.get("score", 0.0))

        print(f"  Top match: [{top_id}] score={top_score:.4f}")
        for i, r in enumerate(results[:3]):
            rid = r.get("chunkId", r.get("id", "?"))
            rscore = r.get("similarity", r.get("score", 0.0))
            above = "✓" if rscore >= SIMILARITY_THRESHOLD else "✗"
            print(f"    {i+1}. [{rid}] {rscore:.4f} {above}")

        is_relevant = top_score >= SIMILARITY_THRESHOLD

        if answerable:
            # mKB auto-generates IDs as {datasetName}-{0-indexed}
            expected_mkb_id = f"{DATASET_NAME}-{expected_id}" if expected_id is not None else None
            correct = is_relevant and (expected_mkb_id is None or top_id == expected_mkb_id)
            status = "PASS" if correct else "FAIL"
            print(f"  Expected: {expected_mkb_id} | Got: {top_id} → {status}")
        else:
            status = "PASS" if not is_relevant else "WARN (score above threshold)"
            print(f"  Expected: no good match | Top score={top_score:.4f} → {status}")

        results_summary.append((query, answerable, status))

    # ── Summary ───────────────────────────────────────────────────────────────
    print(f"\n{'='*65}")
    print("SUMMARY — mKB v1.3.0 with real mimik edgeEngine")
    print("-" * 65)
    passes = sum(1 for _, _, s in results_summary if "PASS" in s)
    warns = sum(1 for _, _, s in results_summary if "WARN" in s)
    total = len(results_summary)
    print(f"  {passes}/{total} PASS  {warns}/{total} WARN")
    for query, _, status in results_summary:
        print(f"  {status:30s}  {query}")

    print(f"\n  Chunk upload format (source-confirmed from mKB JS):")
    print(f"    POST /datasets/{{name}}/chunks")
    print(f"    Content-Type: multipart/form-data")
    print(f"    Form field: 'chunks' (NOT 'file')")
    print(f"    Body: NDJSON lines joined by \\n\\n")
    print(f"      Line 0: {{\"chunkTotal\": N, \"searchPrefix\": null}}")
    print(f"      Line 1+: {{\"chunk\": \"text\", \"embedding\": [...]}}")
    print(f"    chunkId auto-generated as {{datasetName}}-{{index}}")
    print(f"\n  Search format (source-confirmed from mKB JS):")
    print(f"    POST /search")
    print(f"    Body: {{datasetName, prompt, topN}}")
    print(f"    mKB calls mILM internally via GEN_AI_EMBEDDING_URI")


if __name__ == "__main__":
    main()
