import { ipcMain, BrowserWindow } from "electron";
import { readLogs, getStatus, getPort, getHostname, startServer, stopServer, onStatusChange } from "./server.js";
import { loadConfig, saveConfig, isFirstRun, DEFAULT_DATA_DIR, envPath, type EdgebricConfig } from "./config.js";
import { generateCerts, trustCA, certsExist, certPaths } from "./certs.js";
import crypto from "crypto";
import fs from "fs";

export function registerIpcHandlers() {
  // Log viewer
  ipcMain.handle("read-logs", (_event, lines?: number) => {
    return readLogs(lines);
  });

  // Server status
  ipcMain.handle("get-status", () => {
    return { status: getStatus(), port: getPort(), hostname: getHostname() };
  });

  // Server control
  ipcMain.handle("start-server", async () => {
    try {
      await startServer();
      return { success: true };
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : String(err) };
    }
  });

  ipcMain.handle("stop-server", async () => {
    try {
      await stopServer();
      return { success: true };
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : String(err) };
    }
  });

  // Push status changes to all renderer windows
  onStatusChange((status) => {
    for (const win of BrowserWindow.getAllWindows()) {
      win.webContents.send("server-status-changed", status);
    }
  });

  // Config
  ipcMain.handle("get-config", () => {
    return loadConfig();
  });

  ipcMain.handle("is-first-run", () => {
    return isFirstRun();
  });

  ipcMain.handle("get-default-data-dir", () => {
    return DEFAULT_DATA_DIR;
  });

  // Setup wizard — save config
  ipcMain.handle("save-setup", (_event, setupData: {
    dataDir: string;
    port: number;
    oidcIssuer: string;
    oidcClientId: string;
    oidcClientSecret: string;
    adminEmails: string[];
    chatBaseUrl?: string;
    chatModel?: string;
  }) => {
    const config: EdgebricConfig = {
      dataDir: setupData.dataDir,
      port: setupData.port,
      oidcIssuer: setupData.oidcIssuer,
      oidcClientId: setupData.oidcClientId,
      oidcClientSecret: setupData.oidcClientSecret,
      adminEmails: setupData.adminEmails,
      ...(setupData.chatBaseUrl && { chatBaseUrl: setupData.chatBaseUrl }),
      ...(setupData.chatModel && { chatModel: setupData.chatModel }),
    };

    // Ensure data directory exists
    fs.mkdirSync(config.dataDir, { recursive: true });

    saveConfig(config);

    // Generate HTTPS certificates if they don't exist yet
    const hostname = config.hostname ?? "edgebric.local";
    if (!certsExist(config.dataDir)) {
      generateCerts(config.dataDir, hostname, config.port);
      trustCA(config.dataDir);
    }

    const certs = certPaths(config.dataDir);
    const protocol = fs.existsSync(certs.serverCert) ? "https" : "http";

    // Write .env file for the API server
    const sessionSecret = crypto.randomBytes(64).toString("hex");
    const envContent = [
      `# Generated by Edgebric Desktop — ${new Date().toISOString()}`,
      `DATA_DIR=${config.dataDir}`,
      `PORT=${config.port}`,
      `SESSION_SECRET=${sessionSecret}`,
      `OIDC_ISSUER=${config.oidcIssuer}`,
      `OIDC_CLIENT_ID=${config.oidcClientId}`,
      `OIDC_CLIENT_SECRET=${config.oidcClientSecret}`,
      `OIDC_REDIRECT_URI=${protocol}://localhost:${config.port}/api/auth/callback`,
      `ADMIN_EMAILS=${config.adminEmails.join(",")}`,
      `FRONTEND_URL=${protocol}://${hostname}:${config.port}`,
      `TLS_CERT=${certs.serverCert}`,
      `TLS_KEY=${certs.serverKey}`,
      ...(config.chatBaseUrl ? [`CHAT_BASE_URL=${config.chatBaseUrl}`] : []),
      ...(config.chatModel ? [`CHAT_MODEL=${config.chatModel}`] : []),
      "",
    ].join("\n");

    const envFile = envPath(config.dataDir);
    fs.writeFileSync(envFile, envContent, "utf8");

    return { success: true };
  });
}
