import { ipcMain, BrowserWindow } from "electron";
import { readLogs, getStatus, getPort, getHostname, startServer, stopServer, onStatusChange } from "./server.js";
import { loadConfig, saveConfig, isFirstRun, DEFAULT_DATA_DIR, envPath, type EdgebricConfig } from "./config.js";
import { generateCerts, trustCA, certsExist, certPaths } from "./certs.js";
import {
  isOllamaInstalled,
  isOllamaRunning,
  getInstalledVersion,
  downloadOllama,
  startOllama,
  stopOllama,
} from "./ollama.js";
import crypto from "crypto";
import fs from "fs";

export function registerIpcHandlers() {
  // Log viewer
  ipcMain.handle("read-logs", (_event, lines?: number) => {
    return readLogs(lines);
  });

  // Server status
  ipcMain.handle("get-status", () => {
    return { status: getStatus(), port: getPort(), hostname: getHostname() };
  });

  // Server control
  ipcMain.handle("start-server", async () => {
    try {
      await startServer();
      return { success: true };
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : String(err) };
    }
  });

  ipcMain.handle("stop-server", async () => {
    try {
      await stopServer();
      return { success: true };
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : String(err) };
    }
  });

  // Push status changes to all renderer windows
  onStatusChange((status) => {
    for (const win of BrowserWindow.getAllWindows()) {
      win.webContents.send("server-status-changed", status);
    }
  });

  // Config
  ipcMain.handle("get-config", () => {
    return loadConfig();
  });

  ipcMain.handle("is-first-run", () => {
    return isFirstRun();
  });

  ipcMain.handle("get-default-data-dir", () => {
    return DEFAULT_DATA_DIR;
  });

  // Setup wizard — save config
  ipcMain.handle("save-setup", (_event, setupData: {
    mode: "solo" | "admin" | "member";
    dataDir: string;
    port: number;
    oidcIssuer?: string;
    oidcClientId?: string;
    oidcClientSecret?: string;
    adminEmails?: string[];
    chatBaseUrl?: string;
    chatModel?: string;
  }) => {
    const config: EdgebricConfig = {
      mode: setupData.mode,
      dataDir: setupData.dataDir,
      port: setupData.port,
      ...(setupData.oidcIssuer && { oidcIssuer: setupData.oidcIssuer }),
      ...(setupData.oidcClientId && { oidcClientId: setupData.oidcClientId }),
      ...(setupData.oidcClientSecret && { oidcClientSecret: setupData.oidcClientSecret }),
      ...(setupData.adminEmails && { adminEmails: setupData.adminEmails }),
      ...(setupData.chatBaseUrl && { chatBaseUrl: setupData.chatBaseUrl }),
      ...(setupData.chatModel && { chatModel: setupData.chatModel }),
    };

    const isSolo = setupData.mode === "solo";

    // Ensure data directory exists
    fs.mkdirSync(config.dataDir, { recursive: true });

    saveConfig(config);

    // Solo mode: no TLS, no mDNS — localhost only
    const hostname = config.hostname ?? "edgebric.local";
    let protocol = "http";
    let certs = certPaths(config.dataDir);

    if (!isSolo) {
      // Generate HTTPS certificates if they don't exist yet
      if (!certsExist(config.dataDir)) {
        generateCerts(config.dataDir, hostname, config.port);
        trustCA(config.dataDir);
      }
      certs = certPaths(config.dataDir);
      protocol = fs.existsSync(certs.serverCert) ? "https" : "http";
    }

    // Write .env file for the API server
    const sessionSecret = crypto.randomBytes(64).toString("hex");
    const envLines = [
      `# Generated by Edgebric Desktop — ${new Date().toISOString()}`,
      `DATA_DIR=${config.dataDir}`,
      `PORT=${config.port}`,
      `SESSION_SECRET=${sessionSecret}`,
      `AUTH_MODE=${isSolo ? "none" : "oidc"}`,
    ];

    if (!isSolo) {
      envLines.push(
        `OIDC_ISSUER=${config.oidcIssuer ?? ""}`,
        `OIDC_CLIENT_ID=${config.oidcClientId ?? ""}`,
        `OIDC_CLIENT_SECRET=${config.oidcClientSecret ?? ""}`,
        `OIDC_REDIRECT_URI=${protocol}://localhost:${config.port}/api/auth/callback`,
        `ADMIN_EMAILS=${(config.adminEmails ?? []).join(",")}`,
        `FRONTEND_URL=${protocol}://${hostname}:${config.port}`,
        `TLS_CERT=${certs.serverCert}`,
        `TLS_KEY=${certs.serverKey}`,
      );
    } else {
      envLines.push(
        `FRONTEND_URL=http://localhost:${config.port}`,
      );
    }

    if (config.chatBaseUrl) envLines.push(`CHAT_BASE_URL=${config.chatBaseUrl}`);
    if (config.chatModel) envLines.push(`CHAT_MODEL=${config.chatModel}`);

    const envContent = [...envLines,
      "",
    ].join("\n");

    const envFile = envPath(config.dataDir);
    fs.writeFileSync(envFile, envContent, "utf8");

    return { success: true };
  });

  // ─── Ollama ─────────────────────────────────────────────────────────────────

  ipcMain.handle("ollama-status", async () => {
    const config = loadConfig();
    const dataDir = config?.dataDir;
    return {
      installed: isOllamaInstalled(dataDir),
      running: await isOllamaRunning(),
      version: getInstalledVersion(dataDir),
    };
  });

  ipcMain.handle("install-ollama", async (_event, version?: string) => {
    const config = loadConfig();
    try {
      await downloadOllama(version, config?.dataDir, (percent) => {
        for (const win of BrowserWindow.getAllWindows()) {
          win.webContents.send("ollama-download-progress", percent);
        }
      });
      return { success: true };
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : String(err) };
    }
  });

  ipcMain.handle("start-ollama", async () => {
    const config = loadConfig();
    try {
      const result = await startOllama(config?.dataDir);
      return { success: true, external: result.external };
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : String(err) };
    }
  });

  ipcMain.handle("stop-ollama", async () => {
    const config = loadConfig();
    try {
      await stopOllama(config?.dataDir);
      return { success: true };
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : String(err) };
    }
  });
}
