import type { EdgeConfig } from "@edgebric/types";
import type { SearchResult } from "@edgebric/core/rag";

/**
 * Client for mimik mKB (Knowledge Base / vector store service).
 *
 * API confirmed from mKB v1.3.0 JS microservice source inspection:
 *
 * Endpoints:
 *   POST   /datasets                          — create a dataset
 *   GET    /datasets                          — list datasets
 *   DELETE /datasets/{name}                   — delete a dataset
 *   POST   /datasets/{name}/chunks            — upload NDJSON chunks (multipart/form-data, field "chunks")
 *   POST   /search                            — semantic search by prompt text (mKB embeds via mILM internally)
 *   GET    /chunks/{chunkId}                  — retrieve a specific chunk
 *
 * Chunk upload format (NDJSON, NOT JSON array):
 *   - multipart/form-data with form field named "chunks" (not "file")
 *   - Content is NDJSON lines joined by \n\n
 *   - Line 0: {"chunkTotal": N, "searchPrefix": null}
 *   - Line 1+: {"chunk": "text content", "embedding": [float, ...]}
 *   - chunkId is auto-generated by mKB as {datasetName}-{0-indexed-position}
 *
 * Search format: POST /search with {datasetName, prompt, topN}
 *   - mKB calls mILM internally via GEN_AI_EMBEDDING_URI env var to embed the prompt
 *   - Returns array of {chunkId, chunk, similarity, metadata}
 */
export interface MKBClient {
  createDataset(name: string): Promise<void>;
  listDatasets(): Promise<string[]>;
  /** Returns the current number of chunks in the dataset, or 0 if the dataset doesn't exist yet. */
  getDatasetChunkCount(name: string): Promise<number>;
  deleteDataset(name: string): Promise<void>;
  uploadChunks(datasetName: string, chunks: Array<{ text: string; embedding: number[]; metadata?: Record<string, unknown> }>): Promise<void>;
  search(datasetName: string, prompt: string, topN: number): Promise<SearchResult[]>;
}

export function createMKBClient(config: EdgeConfig): MKBClient {
  const base = `${config.baseUrl}/api/mkb/v1`;
  const jsonHeaders = {
    Authorization: `bearer ${config.apiKey}`,
    "Content-Type": "application/json",
  };

  async function createDataset(name: string): Promise<void> {
    const response = await fetch(`${base}/datasets`, {
      method: "POST",
      headers: jsonHeaders,
      body: JSON.stringify({
        datasetName: name,
        model: config.embeddingModel,
      }),
    });
    if (!response.ok) {
      const body = await response.text();
      // mKB v1.3.0 returns 400 with "already exist" message (not 409) — treat as success
      if (response.status === 409 || (response.status === 400 && body.includes("already exist"))) return;
      throw new MKBError("createDataset", response.status, body);
    }
  }

  type DatasetInfo = { datasetName: string; numberOfChunks?: number };

  async function fetchDatasets(): Promise<DatasetInfo[]> {
    const response = await fetch(`${base}/datasets`, { headers: { Authorization: `bearer ${config.apiKey}` } });
    if (!response.ok) {
      throw new MKBError("listDatasets", response.status, await response.text());
    }
    const data = (await response.json()) as { data: DatasetInfo[] };
    return data.data ?? [];
  }

  async function listDatasets(): Promise<string[]> {
    return (await fetchDatasets()).map((d) => d.datasetName);
  }

  async function getDatasetChunkCount(name: string): Promise<number> {
    try {
      const datasets = await fetchDatasets();
      return datasets.find((d) => d.datasetName === name)?.numberOfChunks ?? 0;
    } catch {
      return 0;
    }
  }

  async function deleteDataset(name: string): Promise<void> {
    const response = await fetch(`${base}/datasets/${encodeURIComponent(name)}`, {
      method: "DELETE",
      headers: { Authorization: `bearer ${config.apiKey}` },
    });
    if (!response.ok) {
      throw new MKBError("deleteDataset", response.status, await response.text());
    }
  }

  async function uploadChunks(
    datasetName: string,
    chunks: Array<{ text: string; embedding: number[]; metadata?: Record<string, unknown> }>,
  ): Promise<void> {
    // mKB expects multipart/form-data with a file-like field named "chunks"
    // Content is NDJSON: header line + chunk lines, separated by \n\n
    const lines: string[] = [
      JSON.stringify({ chunkTotal: chunks.length, searchPrefix: null }),
      ...chunks.map((c) => {
        const entry: Record<string, unknown> = { chunk: c.text, embedding: c.embedding };
        if (c.metadata) entry["metadata"] = c.metadata;
        return JSON.stringify(entry);
      }),
    ];
    const ndjson = lines.join("\n\n");

    const formData = new FormData();
    const blob = new Blob([ndjson], { type: "application/octet-stream" });
    formData.append("chunks", blob, "chunks.mdf");

    const response = await fetch(`${base}/datasets/${encodeURIComponent(datasetName)}/chunks`, {
      method: "POST",
      headers: { Authorization: `bearer ${config.apiKey}` }, // No Content-Type — FormData sets boundary
      body: formData,
    });

    if (!response.ok) {
      throw new MKBError("uploadChunks", response.status, await response.text());
    }
    // Response is SSE streaming upload progress — consume and discard
    await response.text();
  }

  async function search(datasetName: string, prompt: string, topN: number): Promise<SearchResult[]> {
    // mKB embeds the prompt internally via GEN_AI_EMBEDDING_URI → mILM
    const response = await fetch(`${base}/search`, {
      method: "POST",
      headers: jsonHeaders,
      body: JSON.stringify({ datasetName, prompt, topN }),
    });

    // 404 means the dataset hasn't been created yet (no documents uploaded).
    // Return empty results — the orchestrator will produce a clean "no answer" response.
    if (response.status === 404) return [];
    if (!response.ok) {
      throw new MKBError("search", response.status, await response.text());
    }

    const data = (await response.json()) as
      | Array<{ chunkId: string; chunk: string; similarity: number; metadata?: Record<string, unknown> }>
      | { data: Array<{ chunkId: string; chunk: string; similarity: number; metadata?: Record<string, unknown> }> };

    const items = Array.isArray(data) ? data : (data.data ?? []);

    return items.map((r) => ({
      chunkId: r.chunkId,
      chunk: r.chunk,
      similarity: r.similarity,
      metadata: (r.metadata as unknown as SearchResult["metadata"]) ?? {
        sourceDocument: "",
        sectionPath: [],
        pageNumber: 0,
        heading: "",
        chunkIndex: 0,
      },
    }));
  }

  return { createDataset, listDatasets, getDatasetChunkCount, deleteDataset, uploadChunks, search };
}

export class MKBError extends Error {
  constructor(
    public readonly operation: string,
    public readonly status: number,
    public readonly body: string,
  ) {
    super(`mKB ${operation} failed (HTTP ${status}): ${body}`);
    this.name = "MKBError";
  }
}
