/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellModelsRouteImport } from './routes/_shell/models'
import { Route as ShellDocumentsRouteImport } from './routes/_shell/documents'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell/analytics'
import { Route as ShellAccountRouteImport } from './routes/_shell/account'
import { Route as ShellConversationsIdRouteImport } from './routes/_shell/conversations.$id'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModelsRoute = ShellModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentsRoute = ShellDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAccountRoute = ShellAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConversationsIdRoute = ShellConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/account': typeof ShellAccountRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/documents': typeof ShellDocumentsRoute
  '/models': typeof ShellModelsRoute
  '/settings': typeof ShellSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/conversations/$id': typeof ShellConversationsIdRoute
}
export interface FileRoutesByTo {
  '/account': typeof ShellAccountRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/documents': typeof ShellDocumentsRoute
  '/models': typeof ShellModelsRoute
  '/settings': typeof ShellSettingsRoute
  '/': typeof ShellIndexRoute
  '/admin': typeof AdminIndexRoute
  '/conversations/$id': typeof ShellConversationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/account': typeof ShellAccountRoute
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/documents': typeof ShellDocumentsRoute
  '/_shell/models': typeof ShellModelsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/': typeof ShellIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_shell/conversations/$id': typeof ShellConversationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/analytics'
    | '/documents'
    | '/models'
    | '/settings'
    | '/admin/'
    | '/conversations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/analytics'
    | '/documents'
    | '/models'
    | '/settings'
    | '/'
    | '/admin'
    | '/conversations/$id'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/account'
    | '/_shell/analytics'
    | '/_shell/documents'
    | '/_shell/models'
    | '/_shell/settings'
    | '/_shell/'
    | '/admin/'
    | '/_shell/conversations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/models': {
      id: '/_shell/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ShellModelsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documents': {
      id: '/_shell/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ShellDocumentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/account': {
      id: '/_shell/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShellAccountRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/conversations/$id': {
      id: '/_shell/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof ShellConversationsIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAccountRoute: typeof ShellAccountRoute
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellDocumentsRoute: typeof ShellDocumentsRoute
  ShellModelsRoute: typeof ShellModelsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellConversationsIdRoute: typeof ShellConversationsIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAccountRoute: ShellAccountRoute,
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellDocumentsRoute: ShellDocumentsRoute,
  ShellModelsRoute: ShellModelsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellConversationsIdRoute: ShellConversationsIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
