/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellOrganizationRouteImport } from './routes/_shell/organization'
import { Route as ShellModelsRouteImport } from './routes/_shell/models'
import { Route as ShellLibraryRouteImport } from './routes/_shell/library'
import { Route as ShellEscalationsRouteImport } from './routes/_shell/escalations'
import { Route as ShellDocumentsRouteImport } from './routes/_shell/documents'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell/analytics'
import { Route as ShellAdminGuideRouteImport } from './routes/_shell/admin-guide'
import { Route as ShellAccountRouteImport } from './routes/_shell/account'
import { Route as ShellConversationsIdRouteImport } from './routes/_shell/conversations.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOrganizationRoute = ShellOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModelsRoute = ShellModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLibraryRoute = ShellLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEscalationsRoute = ShellEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentsRoute = ShellDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminGuideRoute = ShellAdminGuideRouteImport.update({
  id: '/admin-guide',
  path: '/admin-guide',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAccountRoute = ShellAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConversationsIdRoute = ShellConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/account': typeof ShellAccountRoute
  '/admin-guide': typeof ShellAdminGuideRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/documents': typeof ShellDocumentsRoute
  '/escalations': typeof ShellEscalationsRoute
  '/library': typeof ShellLibraryRoute
  '/models': typeof ShellModelsRoute
  '/organization': typeof ShellOrganizationRoute
  '/settings': typeof ShellSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/conversations/$id': typeof ShellConversationsIdRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/account': typeof ShellAccountRoute
  '/admin-guide': typeof ShellAdminGuideRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/documents': typeof ShellDocumentsRoute
  '/escalations': typeof ShellEscalationsRoute
  '/library': typeof ShellLibraryRoute
  '/models': typeof ShellModelsRoute
  '/organization': typeof ShellOrganizationRoute
  '/settings': typeof ShellSettingsRoute
  '/': typeof ShellIndexRoute
  '/admin': typeof AdminIndexRoute
  '/conversations/$id': typeof ShellConversationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_shell/account': typeof ShellAccountRoute
  '/_shell/admin-guide': typeof ShellAdminGuideRoute
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/documents': typeof ShellDocumentsRoute
  '/_shell/escalations': typeof ShellEscalationsRoute
  '/_shell/library': typeof ShellLibraryRoute
  '/_shell/models': typeof ShellModelsRoute
  '/_shell/organization': typeof ShellOrganizationRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/': typeof ShellIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_shell/conversations/$id': typeof ShellConversationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/admin-guide'
    | '/analytics'
    | '/documents'
    | '/escalations'
    | '/library'
    | '/models'
    | '/organization'
    | '/settings'
    | '/admin/'
    | '/conversations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/admin-guide'
    | '/analytics'
    | '/documents'
    | '/escalations'
    | '/library'
    | '/models'
    | '/organization'
    | '/settings'
    | '/'
    | '/admin'
    | '/conversations/$id'
  id:
    | '__root__'
    | '/_shell'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/_shell/account'
    | '/_shell/admin-guide'
    | '/_shell/analytics'
    | '/_shell/documents'
    | '/_shell/escalations'
    | '/_shell/library'
    | '/_shell/models'
    | '/_shell/organization'
    | '/_shell/settings'
    | '/_shell/'
    | '/admin/'
    | '/_shell/conversations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/organization': {
      id: '/_shell/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof ShellOrganizationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/models': {
      id: '/_shell/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ShellModelsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/library': {
      id: '/_shell/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ShellLibraryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/escalations': {
      id: '/_shell/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof ShellEscalationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documents': {
      id: '/_shell/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ShellDocumentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin-guide': {
      id: '/_shell/admin-guide'
      path: '/admin-guide'
      fullPath: '/admin-guide'
      preLoaderRoute: typeof ShellAdminGuideRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/account': {
      id: '/_shell/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShellAccountRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/conversations/$id': {
      id: '/_shell/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof ShellConversationsIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAccountRoute: typeof ShellAccountRoute
  ShellAdminGuideRoute: typeof ShellAdminGuideRoute
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellDocumentsRoute: typeof ShellDocumentsRoute
  ShellEscalationsRoute: typeof ShellEscalationsRoute
  ShellLibraryRoute: typeof ShellLibraryRoute
  ShellModelsRoute: typeof ShellModelsRoute
  ShellOrganizationRoute: typeof ShellOrganizationRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellConversationsIdRoute: typeof ShellConversationsIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAccountRoute: ShellAccountRoute,
  ShellAdminGuideRoute: ShellAdminGuideRoute,
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellDocumentsRoute: ShellDocumentsRoute,
  ShellEscalationsRoute: ShellEscalationsRoute,
  ShellLibraryRoute: ShellLibraryRoute,
  ShellModelsRoute: ShellModelsRoute,
  ShellOrganizationRoute: ShellOrganizationRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellConversationsIdRoute: ShellConversationsIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
