/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AcknowledgmentsRouteImport } from './routes/acknowledgments'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellServiceRouteImport } from './routes/_shell/service'
import { Route as ShellOrganizationRouteImport } from './routes/_shell/organization'
import { Route as ShellModelsRouteImport } from './routes/_shell/models'
import { Route as ShellLibraryRouteImport } from './routes/_shell/library'
import { Route as ShellIntegrationsRouteImport } from './routes/_shell/integrations'
import { Route as ShellGroupChatsRouteImport } from './routes/_shell/group-chats'
import { Route as ShellDocumentsRouteImport } from './routes/_shell/documents'
import { Route as ShellAccountRouteImport } from './routes/_shell/account'
import { Route as ShellGroupChatsIdRouteImport } from './routes/_shell/group-chats.$id'
import { Route as ShellConversationsIdRouteImport } from './routes/_shell/conversations.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AcknowledgmentsRoute = AcknowledgmentsRouteImport.update({
  id: '/acknowledgments',
  path: '/acknowledgments',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellServiceRoute = ShellServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOrganizationRoute = ShellOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModelsRoute = ShellModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLibraryRoute = ShellLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntegrationsRoute = ShellIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGroupChatsRoute = ShellGroupChatsRouteImport.update({
  id: '/group-chats',
  path: '/group-chats',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentsRoute = ShellDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAccountRoute = ShellAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGroupChatsIdRoute = ShellGroupChatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellGroupChatsRoute,
} as any)
const ShellConversationsIdRoute = ShellConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/acknowledgments': typeof AcknowledgmentsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/account': typeof ShellAccountRoute
  '/documents': typeof ShellDocumentsRoute
  '/group-chats': typeof ShellGroupChatsRouteWithChildren
  '/integrations': typeof ShellIntegrationsRoute
  '/library': typeof ShellLibraryRoute
  '/models': typeof ShellModelsRoute
  '/organization': typeof ShellOrganizationRoute
  '/service': typeof ShellServiceRoute
  '/settings': typeof ShellSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/conversations/$id': typeof ShellConversationsIdRoute
  '/group-chats/$id': typeof ShellGroupChatsIdRoute
}
export interface FileRoutesByTo {
  '/acknowledgments': typeof AcknowledgmentsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/account': typeof ShellAccountRoute
  '/documents': typeof ShellDocumentsRoute
  '/group-chats': typeof ShellGroupChatsRouteWithChildren
  '/integrations': typeof ShellIntegrationsRoute
  '/library': typeof ShellLibraryRoute
  '/models': typeof ShellModelsRoute
  '/organization': typeof ShellOrganizationRoute
  '/service': typeof ShellServiceRoute
  '/settings': typeof ShellSettingsRoute
  '/': typeof ShellIndexRoute
  '/admin': typeof AdminIndexRoute
  '/conversations/$id': typeof ShellConversationsIdRoute
  '/group-chats/$id': typeof ShellGroupChatsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/acknowledgments': typeof AcknowledgmentsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_shell/account': typeof ShellAccountRoute
  '/_shell/documents': typeof ShellDocumentsRoute
  '/_shell/group-chats': typeof ShellGroupChatsRouteWithChildren
  '/_shell/integrations': typeof ShellIntegrationsRoute
  '/_shell/library': typeof ShellLibraryRoute
  '/_shell/models': typeof ShellModelsRoute
  '/_shell/organization': typeof ShellOrganizationRoute
  '/_shell/service': typeof ShellServiceRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/': typeof ShellIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_shell/conversations/$id': typeof ShellConversationsIdRoute
  '/_shell/group-chats/$id': typeof ShellGroupChatsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acknowledgments'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/documents'
    | '/group-chats'
    | '/integrations'
    | '/library'
    | '/models'
    | '/organization'
    | '/service'
    | '/settings'
    | '/admin/'
    | '/conversations/$id'
    | '/group-chats/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/acknowledgments'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/documents'
    | '/group-chats'
    | '/integrations'
    | '/library'
    | '/models'
    | '/organization'
    | '/service'
    | '/settings'
    | '/'
    | '/admin'
    | '/conversations/$id'
    | '/group-chats/$id'
  id:
    | '__root__'
    | '/_shell'
    | '/acknowledgments'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/_shell/account'
    | '/_shell/documents'
    | '/_shell/group-chats'
    | '/_shell/integrations'
    | '/_shell/library'
    | '/_shell/models'
    | '/_shell/organization'
    | '/_shell/service'
    | '/_shell/settings'
    | '/_shell/'
    | '/admin/'
    | '/_shell/conversations/$id'
    | '/_shell/group-chats/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AcknowledgmentsRoute: typeof AcknowledgmentsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acknowledgments': {
      id: '/acknowledgments'
      path: '/acknowledgments'
      fullPath: '/acknowledgments'
      preLoaderRoute: typeof AcknowledgmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/service': {
      id: '/_shell/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ShellServiceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/organization': {
      id: '/_shell/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof ShellOrganizationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/models': {
      id: '/_shell/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ShellModelsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/library': {
      id: '/_shell/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ShellLibraryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/integrations': {
      id: '/_shell/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof ShellIntegrationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/group-chats': {
      id: '/_shell/group-chats'
      path: '/group-chats'
      fullPath: '/group-chats'
      preLoaderRoute: typeof ShellGroupChatsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documents': {
      id: '/_shell/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ShellDocumentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/account': {
      id: '/_shell/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShellAccountRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/group-chats/$id': {
      id: '/_shell/group-chats/$id'
      path: '/$id'
      fullPath: '/group-chats/$id'
      preLoaderRoute: typeof ShellGroupChatsIdRouteImport
      parentRoute: typeof ShellGroupChatsRoute
    }
    '/_shell/conversations/$id': {
      id: '/_shell/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof ShellConversationsIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellGroupChatsRouteChildren {
  ShellGroupChatsIdRoute: typeof ShellGroupChatsIdRoute
}

const ShellGroupChatsRouteChildren: ShellGroupChatsRouteChildren = {
  ShellGroupChatsIdRoute: ShellGroupChatsIdRoute,
}

const ShellGroupChatsRouteWithChildren = ShellGroupChatsRoute._addFileChildren(
  ShellGroupChatsRouteChildren,
)

interface ShellRouteChildren {
  ShellAccountRoute: typeof ShellAccountRoute
  ShellDocumentsRoute: typeof ShellDocumentsRoute
  ShellGroupChatsRoute: typeof ShellGroupChatsRouteWithChildren
  ShellIntegrationsRoute: typeof ShellIntegrationsRoute
  ShellLibraryRoute: typeof ShellLibraryRoute
  ShellModelsRoute: typeof ShellModelsRoute
  ShellOrganizationRoute: typeof ShellOrganizationRoute
  ShellServiceRoute: typeof ShellServiceRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellConversationsIdRoute: typeof ShellConversationsIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAccountRoute: ShellAccountRoute,
  ShellDocumentsRoute: ShellDocumentsRoute,
  ShellGroupChatsRoute: ShellGroupChatsRouteWithChildren,
  ShellIntegrationsRoute: ShellIntegrationsRoute,
  ShellLibraryRoute: ShellLibraryRoute,
  ShellModelsRoute: ShellModelsRoute,
  ShellOrganizationRoute: ShellOrganizationRoute,
  ShellServiceRoute: ShellServiceRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellConversationsIdRoute: ShellConversationsIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AcknowledgmentsRoute: AcknowledgmentsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
